// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public enum CloudFlareStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Connected")]
        #pragma warning disable CS1591
        Connected,
        #pragma warning restore CS1591
        [EnumMember(Value = "Disconnected")]
        #pragma warning disable CS1591
        Disconnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "Error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
