// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public enum InterfaceIp_kind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "primary")]
        #pragma warning disable CS1591
        Primary,
        #pragma warning restore CS1591
        [EnumMember(Value = "secondary")]
        #pragma warning disable CS1591
        Secondary,
        #pragma warning restore CS1591
    }
}
