// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    /// <summary>Enhance Licence status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LicenceStatus
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "suspended")]
        #pragma warning disable CS1591
        Suspended,
        #pragma warning restore CS1591
        [EnumMember(Value = "trial")]
        #pragma warning disable CS1591
        Trial,
        #pragma warning restore CS1591
        [EnumMember(Value = "unpaid")]
        #pragma warning disable CS1591
        Unpaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
