// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MaintenanceMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "activate")]
        #pragma warning disable CS1591
        Activate,
        #pragma warning restore CS1591
        [EnumMember(Value = "deactivate")]
        #pragma warning disable CS1591
        Deactivate,
        #pragma warning restore CS1591
    }
}
