// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ServerStatusAction
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "gracefulReboot")]
        #pragma warning disable CS1591
        GracefulReboot,
        #pragma warning restore CS1591
        [EnumMember(Value = "forceReboot")]
        #pragma warning disable CS1591
        ForceReboot,
        #pragma warning restore CS1591
    }
}
