// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public enum UiPreferencesViewKind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "list")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
        [EnumMember(Value = "grid")]
        #pragma warning disable CS1591
        Grid,
        #pragma warning restore CS1591
    }
}
