// <auto-generated/>
#pragma warning disable CS0618
using Enhance.Client.Orgs.Item.Websites.Item.Domains.Item.Screenshot.Take;
using Enhance.Client.Orgs.Item.Websites.Item.Domains.Item.Screenshot.Timestamp;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Enhance.Client.Orgs.Item.Websites.Item.Domains.Item.Screenshot
{
    /// <summary>
    /// Builds and executes requests for operations under \orgs\{org_id}\websites\{website_id}\domains\{domain_id}\screenshot
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class ScreenshotRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The take property</summary>
        public global::Enhance.Client.Orgs.Item.Websites.Item.Domains.Item.Screenshot.Take.TakeRequestBuilder Take
        {
            get => new global::Enhance.Client.Orgs.Item.Websites.Item.Domains.Item.Screenshot.Take.TakeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timestamp property</summary>
        public global::Enhance.Client.Orgs.Item.Websites.Item.Domains.Item.Screenshot.Timestamp.TimestampRequestBuilder Timestamp
        {
            get => new global::Enhance.Client.Orgs.Item.Websites.Item.Domains.Item.Screenshot.Timestamp.TimestampRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.Orgs.Item.Websites.Item.Domains.Item.Screenshot.ScreenshotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScreenshotRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org_id}/websites/{website_id}/domains/{domain_id}/screenshot", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.Orgs.Item.Websites.Item.Domains.Item.Screenshot.ScreenshotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScreenshotRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org_id}/websites/{website_id}/domains/{domain_id}/screenshot", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
