// <auto-generated/>
#pragma warning disable CS0618
using Enhance.Client.Install.Compatible_versions.Controld;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Enhance.Client.Install.Compatible_versions
{
    /// <summary>
    /// Builds and executes requests for operations under \install\compatible_versions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Compatible_versionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The controld property</summary>
        public global::Enhance.Client.Install.Compatible_versions.Controld.ControldRequestBuilder Controld
        {
            get => new global::Enhance.Client.Install.Compatible_versions.Controld.ControldRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.Install.Compatible_versions.Compatible_versionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Compatible_versionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/install/compatible_versions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.Install.Compatible_versions.Compatible_versionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Compatible_versionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/install/compatible_versions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
