// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActivityServerEntity_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "server")]
        #pragma warning disable CS1591
        Server,
        #pragma warning restore CS1591
    }
}
