// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public enum ImportKind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cPanel")]
        #pragma warning disable CS1591
        CPanel,
        #pragma warning restore CS1591
        [EnumMember(Value = "plesk")]
        #pragma warning disable CS1591
        Plesk,
        #pragma warning restore CS1591
    }
}
