// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrgUpdate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The isSuspended property</summary>
        public bool? IsSuspended { get; set; }
        /// <summary>The locale property</summary>
        public global::Enhance.Client.Models.CPLocale? Locale { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The slackNotificationWebhookUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Enhance.Client.Models.OrgUpdate.OrgUpdate_slackNotificationWebhookUrl? SlackNotificationWebhookUrl { get; set; }
#nullable restore
#else
        public global::Enhance.Client.Models.OrgUpdate.OrgUpdate_slackNotificationWebhookUrl SlackNotificationWebhookUrl { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Enhance.Client.Models.Status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.Models.OrgUpdate"/> and sets the default values.
        /// </summary>
        public OrgUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Enhance.Client.Models.OrgUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Enhance.Client.Models.OrgUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Enhance.Client.Models.OrgUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "isSuspended", n => { IsSuspended = n.GetBoolValue(); } },
                { "locale", n => { Locale = n.GetEnumValue<global::Enhance.Client.Models.CPLocale>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "slackNotificationWebhookUrl", n => { SlackNotificationWebhookUrl = n.GetObjectValue<global::Enhance.Client.Models.OrgUpdate.OrgUpdate_slackNotificationWebhookUrl>(global::Enhance.Client.Models.OrgUpdate.OrgUpdate_slackNotificationWebhookUrl.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Enhance.Client.Models.Status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("isSuspended", IsSuspended);
            writer.WriteEnumValue<global::Enhance.Client.Models.CPLocale>("locale", Locale);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Enhance.Client.Models.OrgUpdate.OrgUpdate_slackNotificationWebhookUrl>("slackNotificationWebhookUrl", SlackNotificationWebhookUrl);
            writer.WriteEnumValue<global::Enhance.Client.Models.Status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Enhance.Client.Models.Unset"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrgUpdate_slackNotificationWebhookUrl : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Enhance.Client.Models.Unset"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Enhance.Client.Models.Unset? Unset { get; set; }
#nullable restore
#else
            public global::Enhance.Client.Models.Unset Unset { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Enhance.Client.Models.OrgUpdate.OrgUpdate_slackNotificationWebhookUrl"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Enhance.Client.Models.OrgUpdate.OrgUpdate_slackNotificationWebhookUrl CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Enhance.Client.Models.OrgUpdate.OrgUpdate_slackNotificationWebhookUrl();
                if("Unset".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.Unset = new global::Enhance.Client.Models.Unset();
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(Unset != null)
                {
                    return Unset.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(Unset != null)
                {
                    writer.WriteObjectValue<global::Enhance.Client.Models.Unset>(null, Unset);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
