// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ResourceCheckConflictKind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "mysqlUser")]
        #pragma warning disable CS1591
        MysqlUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "mysqlDb")]
        #pragma warning disable CS1591
        MysqlDb,
        #pragma warning restore CS1591
        [EnumMember(Value = "ftpUser")]
        #pragma warning disable CS1591
        FtpUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "mailboxForwarder")]
        #pragma warning disable CS1591
        MailboxForwarder,
        #pragma warning restore CS1591
        [EnumMember(Value = "mailbox")]
        #pragma warning disable CS1591
        Mailbox,
        #pragma warning restore CS1591
        [EnumMember(Value = "domain")]
        #pragma warning disable CS1591
        Domain,
        #pragma warning restore CS1591
    }
}
