// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ServiceStatusAction
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "gracefulRestart")]
        #pragma warning disable CS1591
        GracefulRestart,
        #pragma warning restore CS1591
        [EnumMember(Value = "forceRestart")]
        #pragma warning disable CS1591
        ForceRestart,
        #pragma warning restore CS1591
    }
}
