// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ServerRole
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "backup")]
        #pragma warning disable CS1591
        Backup,
        #pragma warning restore CS1591
        [EnumMember(Value = "database")]
        #pragma warning disable CS1591
        Database,
        #pragma warning restore CS1591
        [EnumMember(Value = "application")]
        #pragma warning disable CS1591
        Application,
        #pragma warning restore CS1591
        [EnumMember(Value = "dns")]
        #pragma warning disable CS1591
        Dns,
        #pragma warning restore CS1591
    }
}
