// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WPPluginUpdateAvailable
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "available")]
        #pragma warning disable CS1591
        Available,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
