// <auto-generated/>
#pragma warning disable CS0618
using Enhance.Client.Orgs.Item.Import.Server.Item;
using Enhance.Client.Orgs.Item.Import.Server.Settings;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Enhance.Client.Orgs.Item.Import.Server
{
    /// <summary>
    /// Builds and executes requests for operations under \orgs\{org_id}\import\server
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The settings property</summary>
        public global::Enhance.Client.Orgs.Item.Import.Server.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Enhance.Client.Orgs.Item.Import.Server.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Enhance.Client.orgs.item.import.server.item collection</summary>
        /// <param name="position">The UUID of the server</param>
        /// <returns>A <see cref="global::Enhance.Client.Orgs.Item.Import.Server.Item.WithServer_ItemRequestBuilder"/></returns>
        public global::Enhance.Client.Orgs.Item.Import.Server.Item.WithServer_ItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("server_id", position);
                return new global::Enhance.Client.Orgs.Item.Import.Server.Item.WithServer_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Enhance.Client.orgs.item.import.server.item collection</summary>
        /// <param name="position">The UUID of the server</param>
        /// <returns>A <see cref="global::Enhance.Client.Orgs.Item.Import.Server.Item.WithServer_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Enhance.Client.Orgs.Item.Import.Server.Item.WithServer_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("server_id", position);
                return new global::Enhance.Client.Orgs.Item.Import.Server.Item.WithServer_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.Orgs.Item.Import.Server.ServerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org_id}/import/server", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.Orgs.Item.Import.Server.ServerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org_id}/import/server", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
