// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Orgs.Item.Import.Server.Item.CachedDomains
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortByQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "domain")]
        #pragma warning disable CS1591
        Domain,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "kind")]
        #pragma warning disable CS1591
        Kind,
        #pragma warning restore CS1591
    }
}
