// <auto-generated/>
#pragma warning disable CS0618
using Enhance.Client.Websites.Item.Available_php_extensions;
using Enhance.Client.Websites.Item.Php_extensions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Enhance.Client.Websites.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \websites\{website_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class WithWebsite_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The available_php_extensions property</summary>
        public global::Enhance.Client.Websites.Item.Available_php_extensions.Available_php_extensionsRequestBuilder Available_php_extensions
        {
            get => new global::Enhance.Client.Websites.Item.Available_php_extensions.Available_php_extensionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The php_extensions property</summary>
        public global::Enhance.Client.Websites.Item.Php_extensions.Php_extensionsRequestBuilder Php_extensions
        {
            get => new global::Enhance.Client.Websites.Item.Php_extensions.Php_extensionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.Websites.Item.WithWebsite_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWebsite_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/websites/{website_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.Websites.Item.WithWebsite_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWebsite_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/websites/{website_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
