// <auto-generated/>
#pragma warning disable CS0618
using Enhance.Client.Models;
using Enhance.Client.V2.Servers.Item.DatabaseRole.Restart;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Enhance.Client.V2.Servers.Item.DatabaseRole
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\servers\{server_id}\database-role
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DatabaseRoleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The restart property</summary>
        public global::Enhance.Client.V2.Servers.Item.DatabaseRole.Restart.RestartRequestBuilder Restart
        {
            get => new global::Enhance.Client.V2.Servers.Item.DatabaseRole.Restart.RestartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DatabaseRoleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/servers/{server_id}/database-role{?mysqlKind*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DatabaseRoleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/servers/{server_id}/database-role{?mysqlKind*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets the MySQL kind for a given server.
        /// </summary>
        /// <returns>A <see cref="global::Enhance.Client.Models.MysqlKind"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Enhance.Client.Models.MysqlKind?> GetAsync(Action<RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Enhance.Client.Models.MysqlKind?> GetAsync(Action<RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<global::Enhance.Client.Models.MysqlKind?>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Enables the database role on a given ServerUuid
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PutAsync(Action<RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PutAsync(Action<RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets the MySQL kind for a given server.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Enables the database role on a given ServerUuid
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets the MySQL kind for a given server.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DatabaseRoleRequestBuilderGetQueryParameters 
        {
            [Obsolete("This property is deprecated, use MysqlKindAsMysqlKind instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("mysqlKind")]
            public string? MysqlKind { get; set; }
#nullable restore
#else
            [QueryParameter("mysqlKind")]
            public string MysqlKind { get; set; }
#endif
            [QueryParameter("mysqlKind")]
            public global::Enhance.Client.Models.MysqlKind? MysqlKindAsMysqlKind { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DatabaseRoleRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Enables the database role on a given ServerUuid
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DatabaseRoleRequestBuilderPutQueryParameters 
        {
            [Obsolete("This property is deprecated, use MysqlKindAsMysqlKind instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("mysqlKind")]
            public string? MysqlKind { get; set; }
#nullable restore
#else
            [QueryParameter("mysqlKind")]
            public string MysqlKind { get; set; }
#endif
            [QueryParameter("mysqlKind")]
            public global::Enhance.Client.Models.MysqlKind? MysqlKindAsMysqlKind { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DatabaseRoleRequestBuilderPutRequestConfiguration : RequestConfiguration<global::Enhance.Client.V2.Servers.Item.DatabaseRole.DatabaseRoleRequestBuilder.DatabaseRoleRequestBuilderPutQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
