// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Orgs.Item.Customers
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public enum GetSortByQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "owner")]
        #pragma warning disable CS1591
        Owner,
        #pragma warning restore CS1591
        [EnumMember(Value = "ownerEmail")]
        #pragma warning disable CS1591
        OwnerEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscriptionsCount")]
        #pragma warning disable CS1591
        SubscriptionsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "websitesCount")]
        #pragma warning disable CS1591
        WebsitesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "createdAt")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
    }
}
