// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enhance.Client.Orgs.Item.Stats.Websites.Added
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public enum GetTimeIntervalQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "hour")]
        #pragma warning disable CS1591
        Hour,
        #pragma warning restore CS1591
        [EnumMember(Value = "day")]
        #pragma warning disable CS1591
        Day,
        #pragma warning restore CS1591
        [EnumMember(Value = "month")]
        #pragma warning disable CS1591
        Month,
        #pragma warning restore CS1591
    }
}
